<a href="https://colab.research.google.com/github/VitalyGladyshev/gb_nlp/blob/main/HW_05_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ДЗ 05 NLP

Берем отызывы за лето (из архива с материалами или предыдущего занятия)

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
path_otzv = "/content/gdrive/My Drive/Colab Notebooks/NLP/отзывы за лето.xls"

In [4]:
data = pd.read_excel(path_otzv)

In [5]:
data.tail(3)

Rating                                            Content        Date
20656       4                                            Доволен  2017-06-01
20657       1                         Песопаснасть, рут ни нужын  2017-06-01
20658       5  Сбербанк бомбовая компания на сегодняшний день...  2017-06-01

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20659 entries, 0 to 20658
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Rating   20659 non-null  int64 
 1   Content  20656 non-null  object
 2   Date     20659 non-null  object
dtypes: int64(1), object(2)
memory usage: 484.3+ KB


In [19]:
from datetime import datetime

In [20]:
type(data["Date"].values[0])

str

In [36]:
datetime_object = datetime.strptime(data["Date"].values[0], '%Y-%m-%d').date()
datetime_object

datetime.date(2017, 8, 14)

In [34]:
data["Year"] = [datetime.strptime(dt, '%Y-%m-%d').year for dt in data["Date"].values]
data["Month"] = [datetime.strptime(dt, '%Y-%m-%d').month for dt in data["Date"].values]
data["Day"] = [datetime.strptime(dt, '%Y-%m-%d').day for dt in data["Date"].values]
data.head()

Rating                                            Content  ... Month  Day
0       5                                     It just works!  ...     8   14
1       4  В целом удобноное приложение...из минусов хотя...  ...     8   14
2       5                                        Отлично все  ...     8   14
3       5  Стал зависать на 1% работы антивируса. Дальше ...  ...     8   14
4       5                     Очень удобно, работает быстро.  ...     8   14

[5 rows x 6 columns]

## Задание 1

1. Учим conv сеть для классификации - выбить auc выше 0.95

In [38]:
pip install stop_words

  Created wheel for stop-words: filename=stop_words-2018.7.23-cp36-none-any.whl size=32916 sha256=2499d3e4f69a90e2ab0e54cc95240b711816d477eaef720f12d0ad9afe57aaee
  Stored in directory: /root/.cache/pip/wheels/75/37/6a/2b295e03bd07290f0da95c3adb9a74ba95fbc333aa8b0c7c78
Successfully built stop-words


In [40]:
pip install pymorphy2

     |████████████████████████████████| 61kB 1.0MB/s 
     |████████████████████████████████| 8.2MB 500kB/s 


In [41]:
from string import punctuation
from stop_words import get_stop_words
from pymorphy2 import MorphAnalyzer
import re

In [395]:
sw = set(get_stop_words("ru"))
exclude = set(punctuation)
morpher = MorphAnalyzer()

def preprocess_text(txt):
    txt = str(txt)
    txt = "".join(c for c in txt if c not in exclude)
    txt = txt.lower()
    txt = re.sub("\sне", "не", txt)
    txt = [morpher.parse(word)[0].normal_form for word in txt.split() if word not in sw]
    return " ".join(txt)

In [ ]:
# for word in words:
#     print(word, [p.normal_form for p in morph.parse(word)])

In [ ]:
# sw = set(get_stop_words("ru"))
# exclude = set(punctuation)
# morpher = MorphAnalyzer()

# def preprocess_text(txt):
#     txt = str(txt)
#     txt = "".join(c for c in txt if c not in exclude)
#     txt = txt.lower()
#     txt = re.sub("\sне", "не", txt)
#     txt = [str(wd.normal_form) for word in txt.split() for wd in morpher.parse(word) if word not in sw]   # txt = [morpher.parse(word)[0].normal_form for word in txt.split() if word not in sw]
#     return " ".join(txt)

In [396]:
data['Content_prep'] = data['Content'].apply(preprocess_text)
data.tail()

Rating  ...                                       Content_prep
20654       1  ...  шляпас роот право бесполезный прогаразрабыв ох...
20655       5  ...                                              около
20656       4  ...                                          довольный
20657       1  ...                            песопаснастя рута нужын
20658       5  ...  сбербанк бомбовый компания сегодняшний лидер б...

[5 rows x 7 columns]

In [397]:
train_corpus = " ".join(data['Content_prep'])

In [398]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download("punkt")

tokens_tot = word_tokenize(train_corpus)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [399]:
tokens_filtered = [word for word in tokens_tot if word.isalnum()]

In [400]:
from nltk.probability import FreqDist
dist = FreqDist(tokens_filtered)

In [401]:
vocabulary = {v: i+100  for i, v in enumerate(dist) if dist[v]>1}

In [402]:
def text_to_sequence(text, maxlen):
    result = []
    tokens = word_tokenize(text.lower())
    tokens_filtered = [word for word in tokens if word.isalnum()]
    for word in tokens_filtered:
        if word in vocabulary:
            result.append(vocabulary[word])
    padding = [0]*(maxlen-len(result))
    return padding + result[-maxlen:]

In [403]:
data_embeded = np.asarray([text_to_sequence(text, 8) for text in data['Content_prep']], dtype=np.int32)
data_embeded = np.hstack((data_embeded, (data['Month'].values+50).reshape(data['Month'].values.shape[0], 1)))
data_embeded = np.hstack((data_embeded, (data['Day'].values).reshape(data['Day'].values.shape[0], 1)))
data_embeded

array([[   0,    0,    0, ...,  102,   58,   14],
       [ 107,  108,  109, ...,  115,   58,   14],
       [   0,    0,    0, ...,  116,   58,   14],
       ...,
       [   0,    0,    0, ...,  274,   56,    1],
       [   0,    0,    0, ...,  525,   56,    1],
       [   0,  182, 9232, ..., 3814,   56,    1]])

In [404]:
np.max(data_embeded)

12924

In [405]:
# data_embeded = data_embeded / np.max(data_embeded)
# data_embeded

In [406]:
data_embeded[-1]

array([   0,  182, 9232, 4543, 4368, 6421,  427, 3814,   56,    1])

In [407]:
from sklearn.model_selection import train_test_split

In [408]:
y = data['Rating'].values
train_x, valid_x, train_y, valid_y = train_test_split(data_embeded, y, stratify=y, random_state=43)

In [409]:
train_x.shape

(15494, 10)

In [410]:
tr_data = train_x.reshape(train_x.shape[0], train_x.shape[1], 1)
vd_data = valid_x.reshape(valid_x.shape[0], valid_x.shape[1], 1)
tr_data.shape

(15494, 10, 1)

In [411]:
def to_one_hot(Y):
    n_col = np.amax(Y)
    binarized = np.zeros((len(Y), n_col))
    for i in range(len(Y)):
        binarized[i, Y[i]-1] = 1.
    return binarized

In [412]:
train_y_o = to_one_hot(train_y)
valid_y_o = to_one_hot(valid_y)
train_y_o

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

### Строим свёрточную нейронную сеть

In [90]:
import tensorflow as tf

# !pip install -q tensorflow-hub
# !pip install -q tensorflow-datasets
import tensorflow_hub as hub
# import tensorflow_datasets as tfds

import keras

from keras.models import Sequential
from keras.layers import Dense, Conv1D, MaxPooling1D, Dropout, Flatten
from keras.utils import to_categorical

from typing import List, Optional, Dict, Tuple

In [91]:
def calculate_confidence_interval(scores: list, conf_interval: float = 0.95) -> Tuple[float]:
    """
    Вычисление доверительного интервала.

    Parameters
    ----------
    scores: List[float / int]
        Список с оценками изучаемой величины.

    conf_interval: float, optional, default = 0.95
        Уровень доверия для построения интервала.
        Опциональный параметр, по умолчанию, равен 0.95.

    Returns
    -------
    conf_interval: Tuple[float]
        Кортеж с границами доверительного интервала.

    """
    left_bound = np.percentile(
        scores, ((1 - conf_interval) / 2) * 100
    )
    right_bound = np.percentile(
        scores, (conf_interval + ((1 - conf_interval) / 2)) * 100
    )

    return left_bound, right_bound

In [181]:
def net_gen(lay_cnt=1, filters=32, neurons=32):
    # конфигурирование слоев нейросети
    model = Sequential()

    # слои нейросети отвественные за свертку и max-pooling
    model.add(Conv1D(filters, 3, padding='same', activation='sigmoid', input_shape=(tr_data.shape[1], 1)))   # relu
    # model.add(Conv1D(filters, 3, activation='relu'))
    # model.add(MaxPooling1D(pool_size=2))
    model.add(Dropout(0.25))
    if lay_cnt == 2:
        model.add(Conv1D(filters, 3, padding='same', activation='sigmoid')) # relu
        # model.add(MaxPooling1D(pool_size=2))
        model.add(Dropout(0.25))

    # полносвязные слои нейронной сети
    model.add(Flatten())
    model.add(Dense(neurons, activation='sigmoid'))   # relu
    # model.add(Dense(neurons, activation='relu'))))
    model.add(Dropout(0.5))
    model.add(Dense(5, activation='softmax')) # sigmoid'))

    # компиляция модели
    model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),#
                loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
                metrics=[tf.keras.metrics.AUC()])

    return model

In [182]:
def net_iter(model, ep=10, batch_size=64):
    history = model.fit(tr_data,
                        train_y_o,
                        batch_size=batch_size,
                        epochs=ep,
                        validation_data=(vd_data, valid_y_o),
                        shuffle=True,
                        verbose=0)    
    return history.history

In [183]:
summary_data = pd.DataFrame(data=[[0, 0, 0, 0, 0, 0, 0, 0]], 
                            columns=['layers', 'filters', 'neurons', 'mean_train_score', 'mean_val_score', 'variance', 'l_b', 'r_b'])
cnt = 0
f_n = [128, 256]
l_c = [1, 2]
nr = [32, 64]
epochs = 15

# net_res = []

for l_c_i in l_c:
    for f_n_i in f_n:
        for nr_i in nr:
            err_score = []
            err_val_score = []
            print(f"Модель: слоёв {l_c_i}, фильтров {f_n_i}, нейронов {nr_i}, эпох {epochs}\n")
            model = net_gen(filters=f_n_i, lay_cnt=l_c_i, neurons=nr_i)
            model.summary()
            for i in range(5):
                print(f"\tИтерация: {i+1}")
                hist = net_iter(model, ep=epochs)
                # net_res.append(hist)
                err_score.append(hist[list(hist.keys())[1]][-1])
                err_val_score.append(hist[list(hist.keys())[3]][-1])

            vr = np.var(err_val_score)
            l_b, r_b = calculate_confidence_interval(err_val_score)
            mean_err_score, mean_err_val_score = np.mean(err_score), np.mean(err_val_score)
            print(f"Ошибки на train. Средняя: {mean_err_score} список: {err_score}")
            print(f"Ошибки на valid. Средняя: {mean_err_val_score} список: {err_val_score}")
            print(f"Дисперсия ошибки на valid: {vr}")
            print(f"Доверительный интервал: {l_b} - {r_b}\n\n")
            summary_data.loc[cnt, ['layers', 'filters', 'neurons', 'mean_train_score', 
                                    'mean_val_score', 'variance', 'l_b', 'r_b']] = [l_c_i, f_n_i, 
                                    nr_i, np.mean(err_score), np.mean(err_val_score), vr, l_b, r_b]
            cnt += 1

Модель: слоёв 1, фильтров 128, нейронов 32, эпох 15

Model: "sequential_33"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_36 (Conv1D)           (None, 20, 128)           512       
_________________________________________________________________
dropout_59 (Dropout)         (None, 20, 128)           0         
_________________________________________________________________
flatten_32 (Flatten)         (None, 2560)              0         
_________________________________________________________________
dense_64 (Dense)             (None, 32)                81952     
_________________________________________________________________
dropout_60 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_65 (Dense)             (None, 5)                 165       
Total params: 82,629
Trainable params: 82,629
Non-trainable params

In [184]:
summary_data

layers  filters  neurons  ...  variance       l_b       r_b
0     1.0    128.0     32.0  ...       0.0  0.816312  0.816312
1     1.0    128.0     64.0  ...       0.0  0.816312  0.816312
2     1.0    256.0     32.0  ...       0.0  0.816312  0.816312
3     1.0    256.0     64.0  ...       0.0  0.816312  0.816312
4     2.0    128.0     32.0  ...       0.0  0.816312  0.816312
5     2.0    128.0     64.0  ...       0.0  0.816312  0.816312
6     2.0    256.0     32.0  ...       0.0  0.816312  0.816312
7     2.0    256.0     64.0  ...       0.0  0.816312  0.816312

[8 rows x 8 columns]

In [185]:
summary_data.sort_values('mean_val_score', ascending=False)

layers  filters  neurons  ...  variance       l_b       r_b
0     1.0    128.0     32.0  ...       0.0  0.816312  0.816312
1     1.0    128.0     64.0  ...       0.0  0.816312  0.816312
2     1.0    256.0     32.0  ...       0.0  0.816312  0.816312
3     1.0    256.0     64.0  ...       0.0  0.816312  0.816312
4     2.0    128.0     32.0  ...       0.0  0.816312  0.816312
5     2.0    128.0     64.0  ...       0.0  0.816312  0.816312
6     2.0    256.0     32.0  ...       0.0  0.816312  0.816312
7     2.0    256.0     64.0  ...       0.0  0.816312  0.816312

[8 rows x 8 columns]

In [425]:
# конфигурирование слоев нейросети
model = Sequential()

# слои нейросети отвественные за свертку и max-pooling
model.add(Conv1D(128, 3, padding='same', activation='sigmoid', input_shape=(tr_data.shape[1], 1))) # sigmoid'))relu
model.add(Conv1D(128, 3, padding='same', activation='sigmoid'))
model.add(MaxPooling1D(pool_size=2))
# model.add(Dropout(0.25))
# if lay_cnt == 2:
model.add(Conv1D(128, 3, padding='same', activation='sigmoid'))
model.add(Conv1D(128, 3, padding='same', activation='sigmoid'))
model.add(MaxPooling1D(pool_size=2))
#     model.add(Dropout(0.25))

# полносвязные слои нейронной сети
model.add(Flatten())
model.add(Dense(32, activation='sigmoid')) # 'relu'))
# model.add(Dense(neurons, activation='relu'))))
model.add(Dropout(0.5))
model.add(Dense(5, activation='softmax')) # sigmoid'))

# компиляция модели
model.compile(optimizer=tf.keras.optimizers.Adam(1e-3),#
              loss=tf.keras.losses.CategoricalCrossentropy(),
              metrics=[tf.keras.metrics.AUC()])

In [426]:
model.summary()

Model: "sequential_56"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_65 (Conv1D)           (None, 10, 128)           512       
_________________________________________________________________
conv1d_66 (Conv1D)           (None, 10, 128)           49280     
_________________________________________________________________
max_pooling1d_30 (MaxPooling (None, 5, 128)            0         
_________________________________________________________________
conv1d_67 (Conv1D)           (None, 5, 128)            49280     
_________________________________________________________________
conv1d_68 (Conv1D)           (None, 5, 128)            49280     
_________________________________________________________________
max_pooling1d_31 (MaxPooling (None, 2, 128)            0         
_________________________________________________________________
flatten_55 (Flatten)         (None, 256)             

In [427]:
callback = tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3)

In [428]:
hist = model.fit(tr_data,
                 train_y_o,
                 batch_size=64,
                 epochs=1000,
                 validation_data=(vd_data, valid_y_o),
                 callbacks=[callback], 
                 shuffle=True,
                 verbose=1)

Epoch 1/1000
243/243 [==============================] - 5s 19ms/step - loss: 1.0223 - auc_28: 0.8554 - val_loss: 0.8385 - val_auc_28: 0.9074
Epoch 2/1000
243/243 [==============================] - 4s 18ms/step - loss: 0.8663 - auc_28: 0.9011 - val_loss: 0.8251 - val_auc_28: 0.9114
Epoch 3/1000
243/243 [==============================] - 4s 18ms/step - loss: 0.8413 - auc_28: 0.9070 - val_loss: 0.8177 - val_auc_28: 0.9130
Epoch 4/1000
243/243 [==============================] - 5s 19ms/step - loss: 0.8299 - auc_28: 0.9093 - val_loss: 0.8104 - val_auc_28: 0.9143
Epoch 5/1000
243/243 [==============================] - 5s 19ms/step - loss: 0.8236 - auc_28: 0.9106 - val_loss: 0.8274 - val_auc_28: 0.9132
Epoch 6/1000
243/243 [==============================] - 5s 19ms/step - loss: 0.8185 - auc_28: 0.9120 - val_loss: 0.7934 - val_auc_28: 0.9173
Epoch 7/1000
243/243 [==============================] - 4s 18ms/step - loss: 0.8152 - auc_28: 0.9127 - val_loss: 0.8058 - val_auc_28: 0.9156
Epoch 8/1000


## Задание 2

2. Предобучаем word2vec и его эмбединга инициализируем сетку, как влияет на качество?

## Попробуем word2vec с LogisticRegression

In [476]:
from gensim.models import Word2Vec
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import roc_auc_score

from tqdm import tqdm

In [472]:
modelW2V = Word2Vec(sentences=data['Content_prep'].apply(str.split), size=100, window=5, min_count=1)

In [474]:
# modelW2V.wv.vocab

In [482]:
def get_vect_mean(txt):
    vector_w2v = np.zeros(100)
    n_w2v = 0
    for wrd in txt:
        if wrd in modelW2V:
            vector_w2v += modelW2V[wrd]
            n_w2v += 1
    if n_w2v > 0:
        vector_w2v = vector_w2v / n_w2v
    return vector_w2v

In [483]:
y = data['Rating'].values
train_x, valid_x, train_y, valid_y = train_test_split(data['Content_prep'].values, y, stratify=y, random_state=43)

In [484]:
arr_vect = []
for txt in tqdm(train_x):
    arr_vect.append(get_vect_mean(txt))
    
arr_vect_valid = []
for txt in tqdm(valid_x):
    arr_vect_valid.append(get_vect_mean(txt))
    
train_w2v = np.asarray(arr_vect)    
valid_w2v = np.asarray(arr_vect_valid)

  0%|          | 0/15494 [00:00<?, ?it/s]/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: Call to deprecated `__contains__` (Method will be removed in 4.0.0, use self.wv.__contains__() instead).
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  
100%|██████████| 5165/5165 [00:02<00:00, 2539.01it/s]


In [485]:
lgr_w2v = LogisticRegression()

In [487]:
lgr_w2v.fit(train_w2v, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [493]:
y_pred = lgr_w2v.predict_proba(valid_w2v)

In [494]:
y_pred

array([[0.10287767, 0.03456026, 0.04196217, 0.09825563, 0.72234426],
       [0.10420789, 0.03477605, 0.04268068, 0.10391686, 0.71441851],
       [0.08642222, 0.02959195, 0.03714163, 0.10226183, 0.74458237],
       ...,
       [0.10388088, 0.03485177, 0.04247523, 0.10048459, 0.71830753],
       [0.08642222, 0.02959195, 0.03714163, 0.10226183, 0.74458237],
       [0.11915079, 0.03887348, 0.04695596, 0.1053068 , 0.68971298]])

In [499]:
roc_auc_score(to_one_hot(valid_y), y_pred)

0.6669329078901169

## Используем word2vec в CNN